name: web_page
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  flutter_dropzone: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

        
    
    
                                      